; Script generated by Antigravity para Hybrid on Cloud (Nuitka Version)
#define MyAppName "Hybrid on Cloud"
#define MyAppVersion "1.2.0"
#define MyAppPublisher "Hybrid on Cloud"
#define MyAppURL "https://hybridtocloud.com"
#define MyAppExeName "widget.exe"

[Setup]
; Identificador único de la aplicación
AppId={{D3B3E3C5-A8B9-4F5E-9F9C-5D6A8D7B9C0E}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; Forzar actualización del caché de iconos de Windows al instalar/desinstalar
ChangesAssociations=yes
; Puedes descomentar esto si tienes una licencia
;LicenseFile=assets\license.txt
OutputDir=installer
OutputBaseFilename=Instalador_HybridOnCloud
SetupIconFile=assets\icon.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Instalamos únicamente el ejecutable optimizado de Nuitka
Source: "widget.exe"; DestDir: "{app}"; Flags: ignoreversion
; Source: "start_backend.vbs"; DestDir: "{app}"; Flags: ignoreversion
; Nota: Las dependencias y assets ya están empaquetadas dentro del .exe

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
; Iniciar la aplicación después de instalar
Filename: "{app}\{#MyAppExeName}"; Description: "Lanzar {#MyAppName}"; Flags: nowait postinstall skipifsilent
